version: '3.1'

services:

  db:
    image: mysql
    container_name: demo-mysql #you can change this
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=crud_productos
      - MYSQL_PORT=3306
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin
    container_name: demo-phpmyadmin #you can change this
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8090:80"
    restart: always

volumes:
  db_data:
